name: 'hacktoberno'
description: 'Autonuke spammy Hacktoberfest prs'
inputs:
   who-to-greet:
      description: 'Who to greet'
      required: true
      default: 'World'
   shouldCheckout:
      description: whether we should checkout the repo ourselves or use actions/checkout
      required: false
      default: 'false'
outputs:
   time:
      description: 'The time we greeted you'
runs:
   using: 'docker'
   image: 'Dockerfile'
   args:
      - ${{ inputs.who-to-greet }}
      - ${{ inputs.shouldCheckout }}
