on:
   pull_request:
      types:
         - opened
         - synchronize
         - reopened

jobs:
   blocker:
      runs-on: ubuntu-latest
      name: hacktoberno
      steps:
         - name: Clone Repo
           id: clone-repo
           uses: actions/checkout@v2
           with:
              fetch-depth: 3
         - name: Hacktoberno
           id: hacktoberno
           uses: eankeen/hacktoberno-thanks@main
           with:
              shouldCheckout: 'false'
