on:
   pull_request:
      types:
         - opened
         - synchronize
         - reopened

jobs:
   blocker:
      runs-on: ubuntu-latest
      name: hacktoberno
      steps:
         - name: Main step
           id: hello
           uses: eankeen/hacktoberno-thanks@main
           with:
              who-to-greet: 'Mona the Octocat'
         # Use the output from the `hello` step
         - name: Get the output time
           run: echo "The time was ${{ steps.hello.outputs.time }}"
